/**
 * 常量定义
 */

// OpCode常量
const OP_CODE = {
  DISPATCH: 0,
  HEARTBEAT: 1,
  IDENTIFY: 2,
  RESUME: 6,
  RECONNECT: 7,
  INVALID_SESSION: 9,
  HELLO: 10,
  HEARTBEAT_ACK: 11,
  HTTP_CALLBACK_ACK: 12,
  CALLBACK_VALIDATION: 13
};

// 事件类型常量
const EVENT_TYPE = {
  GROUP_AT_MESSAGE_CREATE: 'GROUP_AT_MESSAGE_CREATE',
  DIRECT_MESSAGE_CREATE: 'DIRECT_MESSAGE_CREATE',
  GUILD_CREATE: 'GUILD_CREATE',
  GUILD_MEMBER_ADD: 'GUILD_MEMBER_ADD',
  // ... 其他事件类型
  AT_MESSAGE_CREATE: 'AT_MESSAGE_CREATE',
};

module.exports = {
  OP_CODE,
  EVENT_TYPE
}; 